### ISSUE TITLE
Refactor to use React

### ISSUE THREAD

**Issue by Yurickh** [co-de-sign/cds-hero-maker#1]
I've originally done this as a personal challenge to not use it, and it was wonderful to learn how much easier React makes our lives.

**Comment by leonardodino** [comment]
maybe `preact`?

or something else, to remember again how much of react we take for granted. 😂

**Comment by Yurickh** [comment]
A Preact component would be welcome too!

**Comment by Yurickh** [comment]
I'll be closing this, as it seems to have gotten stale for a year now
