### ISSUE TITLE
🐛 Fix known bugs

### ISSUE THREAD

**Issue by Yurickh** [co-de-sign/cds-hero-maker#4]
This is an umbrella issue for some problems we've encountered in the current tool.

- [x] Looks like the logo svg sometimes bug when exporting the image
<img width="500" alt="screen shot 2018-10-16 at 10 58 52" src="https://user-images.githubusercontent.com/4389850/47021777-79fd1800-d132-11e8-9126-ab3051fd33c9.png">

- [ ] There are indentation issues on the "css" textbox.
> I guess #1 might fix this as a side effect.

**Comment by leonardodino** [comment]
what you mean by _"indentation issues"_?

it's not happening on the sample image, is it?

**Comment by Yurickh** [comment]
Steps to reproduce:

1. Write a multiline string in the `Conteúdo do evento` textbox
2. Edit the number on `Número da edição`
3. Go mad

**Comment by leonardodino** [comment]
definitely the kind of trouble solved with a saner data-flow.
[amen react](http://dan.church/).

**Comment by Yurickh** [comment]
I'll be closing this as it seems no one is working on this for more than a year now.
